---
title: "Auto scate detect"
author: "Matej Stevuliak"
date: "7/15/2019"
output: html_document
---

```{r setup, include=FALSE}
# Make Sure You have all following packages, If not uncoment and run next line:
#source(here('/R/src/config_file.R'))  

#library(data.table)
library(magrittr)   # Needed for pipe operator %>%  
library(tools)
library(dplyr)
library(reshape2)
library(reshape)
library(ggplot2)
library(tidyr)      # Needed for tidy data functions like separate
library(tidyverse)
library(readxl)     # Read xlsx file
library(here)       # Used to set the path to the package dir. on the mashine 
library(knitr)      # Used for tables 
library(kableExtra)


# source the functions used in analysis
source(here('/R/src/analysis_source_functions.R'))

INPUT_PATH  <- here('Data/INPUT/New_format/Matej/Data for pipeline/All')
OUTPUT_PATH <- here('/Data/OUTPUT')
data <- read_xlsx_set(INPUT_PATH, ".xlsx")
```

Inspect Data
```{r}
dm <- data$rates

```





Form the data of well trios in each interval 
```{r}
d <- dm %>%  
  filter(Interval != "Int5") %>% 
  group_by(sample_id,Well, Interval) %>% 
  summarise(mean_OCR = mean(OCR), sd_OCR = sd(OCR), Project = unique(Project), Protocol = unique(Protocol))


sampled <- d %>%
  group_by(sample_id, Interval)

c <- sampled %>% 
  group_by(sample_id, Interval) %>% 
  summarise(pearson  = cor(mean_OCR,sd_OCR, method = "pearson"), 
            spearman = cor(mean_OCR,sd_OCR, method = "spearman") )


#PLOTS
# ALL
ggplot(sampled, aes(mean_OCR,sd_OCR))+
  ggtitle("Normal")+
  geom_point(aes(mean_OCR,sd_OCR, color = Interval), size = 0.5)+
  stat_smooth()+
  theme_bw()

ggplot(sampled)+
  geom_histogram(aes(mean_OCR, fill = "red" ), bins = 100, color = "black")+
  theme_bw()

# INTERVALS 
ggplot(sampled, aes(mean_OCR,sd_OCR))+
  geom_point(aes(mean_OCR,sd_OCR, color = Project), size = 0.5)+
  stat_smooth()+
  facet_wrap(. ~ Interval)+
  ggtitle("Squared root")+
  ylab("SD ")+
  xlab("Mean")+
  theme_bw()

ggplot(c)+
  geom_violin(aes(Interval, pearson), show.legend = FALSE)+
  geom_jitter(aes(Interval, pearson), show.legend = FALSE, size=0.5, width = 0.1)+
  stat_summary(aes(Interval, pearson),color="red")+
  theme_bw()


# SAMPLES

ggplot(c)+
  geom_violin(aes(Interval, pearson), show.legend = FALSE)+
  geom_point(aes(Interval, pearson), show.legend = FALSE)

# ---------------- LOG
dm <- dm %>% mutate(LOCR = log(OCR+1))

d <- dm %>%  
  filter(Interval != "Int5") %>% 
  group_by(sample_id,Well, Interval) %>% 
  summarise(mean_OCR = mean(LOCR), sd_OCR = sd(LOCR), Project = unique(Project), Protocol = unique(Protocol))

sampled <- d %>% 
  group_by(sample_id, Interval) 

c <- sampled %>% 
  group_by(sample_id, Interval) %>% 
  summarise(pearson  = cor(mean_OCR,sd_OCR, method = "pearson"), 
            spearman = cor(mean_OCR,sd_OCR, method = "spearman") )


#PLOTS
# ALL
ggplot(sampled, aes(mean_OCR,sd_OCR))+
  ggtitle("Log")+
  geom_point(aes(mean_OCR,sd_OCR, color = Interval), size = 0.5)+
  stat_smooth()+
  theme_bw()

ggplot(sampled)+
  geom_histogram(aes(mean_OCR, fill = "red" ), bins = 100, color = "black")+
  theme_bw()

# INTERVALS 
ggplot(sampled, aes(mean_OCR,sd_OCR))+
  geom_point(aes(mean_OCR,sd_OCR, color = Project), size = 0.5)+
  stat_smooth()+
  facet_wrap(. ~ Interval)+
  ggtitle("Squared root")+
  ylab("SD ")+
  xlab("Mean")+
  theme_bw()

ggplot(c)+
  geom_violin(aes(Interval, pearson), show.legend = FALSE)+
  geom_jitter(aes(Interval, pearson), show.legend = FALSE, size=0.5, width = 0.1)+
  stat_summary(aes(Interval, pearson),color="red")+
  theme_bw()


# ---------------- Square root

d <- dm %>%  
  filter(Interval != "Int5") %>% 
  group_by(sample_id,Well, Interval) %>% 
  summarise(mean_OCR = mean(Power), sd_OCR = sd(Power), Project = unique(Project), Protocol = unique(Protocol))

sampled <- d %>% 
  group_by(sample_id, Interval) 

c <- sampled %>% 
  group_by(sample_id, Interval) %>% 
  summarise(pearson  = cor(mean_OCR,sd_OCR, method = "pearson"), 
            spearman = cor(mean_OCR,sd_OCR, method = "spearman") )


#PLOTS
# ALL
ggplot(sampled, aes(mean_OCR,sd_OCR))+
  ggtitle("Exponential")+
  geom_point(aes(mean_OCR,sd_OCR, color = Interval), size = 0.5)+
  stat_smooth()+
  theme_bw()

ggplot(sampled)+
  geom_histogram(aes(mean_OCR, fill = "red" ), bins = 100, color = "black")+
  theme_bw()

# INTERVALS 
ggplot(sampled, aes(mean_OCR,sd_OCR))+
  geom_point(aes(mean_OCR,sd_OCR, color = Project), size = 0.5)+
  stat_smooth()+
  facet_wrap(. ~ Interval)+
  ggtitle("Squared root")+
  ylab("SD ")+
  xlab("Mean")+
  theme_bw()

ggplot(c)+
  geom_violin(aes(Interval, pearson), show.legend = FALSE)+
  geom_jitter(aes(Interval, pearson), show.legend = FALSE, size=0.5, width = 0.1)+
  stat_summary(aes(Interval, pearson),color="red")+
  theme_bw()

```




```{r}
d <- dm %>%  
  filter(Interval != "Int5") %>% 
  group_by(sample_id,Well, Interval) %>% 
  summarise(mean_OCR = mean(Power), sd_OCR = sd(Power), Project = unique(Project), Protocol = unique(Protocol))

sampled <- d %>% 
  group_by(sample_id, Interval) 

c <- sampled %>% 
  group_by(sample_id, Interval) %>% 
  summarise(pearson  = cor(mean_OCR,sd_OCR, method = "pearson"), 
            spearman = cor(mean_OCR,sd_OCR, method = "spearman") )


#PLOTS
# ALL
ggplot(sampled, aes(mean_OCR,sd_OCR))+
  geom_point(aes(mean_OCR,sd_OCR, color = Interval))+
  stat_smooth(method = lm)
# INTERVALS 
ggplot(sampled, aes(mean_OCR,sd_OCR))+
  geom_point(aes(mean_OCR,sd_OCR, color = Interval))+
  stat_smooth(method = lm)+
  facet_wrap(. ~ Interval)
# Protocol
ggplot(sampled, aes(mean_OCR,sd_OCR))+
  geom_point(aes(mean_OCR,sd_OCR, color = Protocol))+
  stat_smooth(method = lm)+
  facet_wrap(. ~ Interval + Protocol)
# SAMPLES
ggplot(sampled, aes(mean_OCR,sd_OCR))+
  geom_point(aes(mean_OCR,sd_OCR, color = Interval))+
  stat_smooth(method = lm)+
  facet_wrap(. ~ sample_id)

ggplot(c)+
  geom_violin(aes(Interval, pearson))+
  geom_point(aes(Interval, pearson))+
  geom_line(aes(Interval, pearson, group = sample_id, color = sample_id), size = 0.1)

```
Variation in power coeficient transformation
```{r}
for (i in seq(0.1,1, 0.1 )) {
  
  dm <- dm %>% mutate(Power = OCR^i)
  d <- dm %>%  
  filter(Interval != "Int5") %>% 
  group_by(sample_id,Well, Interval) %>% 
  summarise(mean_OCR = mean(Power), sd_OCR = sd(Power), Project = unique(Project), Protocol = unique(Protocol))

sampled <- d %>% 
  group_by(sample_id, Interval) %>% 
  sample_n(200, replace = T)

c <- sampled %>% 
  group_by(sample_id, Interval) %>% 
  summarise(pearson  = cor(mean_OCR,sd_OCR, method = "pearson"), 
            spearman = cor(mean_OCR,sd_OCR, method = "spearman") )

p1 <- ggplot(sampled, aes(mean_OCR,sd_OCR))+
        ggtitle(paste0("OCR^", i))+
        geom_point(aes(mean_OCR,sd_OCR, color = Interval))+
        stat_smooth(method = lm)
#distribution
p2 <- ggplot(c)+
        geom_violin(aes(Interval, pearson))+
        geom_point(aes(Interval, pearson))
print(p1+theme_bw())
print(p2+theme_bw())
}
```






##### LOOK AT THE 3 injections 

```{r}
for (smpl in unique(dt$sample_id)) {
  d    <- filter(dt, sample_id == smpl)
  plot <- ggplot(d, aes(Measurement, ECAR))+
            ggtitle(paste0("ID: ", smpl))+
            geom_line(aes(group = Well,  linetype = Protocol),size = 0.2, color = "grey") +
            geom_point(aes(Measurement, ECAR))+
            xlab("Interval")#+

  print(plot +theme_bw())
}
```


```{r}
dt <- dm %>% filter(! Measurement %in% c(1,2,3)) %>% mutate(Measurement = Measurement - 3)


  get_intervals <- function(x, y){
    # Identifies Interval form measurement time  and Protocol info. Used with mapply
    # INPUT x = Measurement, y = Protocol
    # OUTPUT = Interval
    return( ifelse(y == "Back", "Back",
            ifelse(grepl(as.character(x), "123"), "Int1",
            ifelse((grepl(as.character(x), "456") & (y == "Olig"|y == "Glyc")), "Int2",
            ifelse((grepl(as.character(x), "456") & y == "FCCP"), "Int3",
            ifelse(grepl(as.character(x), "789") & y == "Glyc" , "Int5",
            ifelse(grepl(as.character(x), "789") & y != "Glyc", "Int4", "Other" )))))))
  }

  
dt$Interval <- mapply(get_intervals, dt$Measurement, dt$Protocol)  
dt <- dt %>% mutate(Time = ifelse(Interval == "Int1" | Interval == "Int2", Measurement,
                              ifelse(Interval == "Int3" | Interval == "Int4", Measurement + 3, Measurement + 6)))

# background

  background <- dt %>%
    filter(Group == "Background") %>%
    group_by(Measurement, plate_id) %>%
    mutate( Z_mod = abs((ECAR - median(ECAR))/mad(ECAR)))


  out        <- background %>% filter(Z_mod > 3.26)
  background <- background %>%
    filter(Z_mod < 3.26) %>%
    mutate(Mean_to_substr = mean(ECAR)) # take mean to substract

  background <- background[!duplicated(background[,"Mean_to_substr"]),] # reduce the data before joining them

  d <- dt %>%
    left_join(background, by = c("Measurement", "plate_id"), suffix  = c("",".y") ) %>%
    mutate(ECAR = ECAR - Mean_to_substr ) %>%
    select(-c(contains("y"),"Z_mod", "Mean_to_substr"))
  
  d <- d  %>% filter(Protocol != "Back")
  d$OCR <- NA
  d$LOCR <- NA
  

write_csv(d, paste0(INPUT_PATH, "Ready for pipeline ECAR"))  
r <- read_csv("../Data/INPUT/New_format/Data for pipeline/3 injectionsReady for pipeline ECAR")

t<-d %>% 
  group_by(sample_id) %>% 
  summarise(n())

```

# Names
```{r}
unique(dm$Protocol)
unique(dm$Project)
unique(dm$sample_id)
unique(dm$Interval)

samples <- dm %>% 
  group_by(sample_id) %>% 
  summarise(n(), plate_id = unique(plate_id), Project = paste0(unique(Project), collapse = ""))


projects <- dm %>% 
  group_by(Project) %>% 
  summarise(N_samples = length(unique(sample_id)), sample_id = paste0(unique(sample_id), collapse = ""))
# filter faulty sample ID
samples <- samples %>% filter(`n()` >= 405)
dm <- dm %>% filter(sample_id %in% samples$sample_id)

# other Interval 
dm <- dm %>% filter(Measurement <= 9)

write_csv(samples, "samples-check.csv")  

```
Plate IDs  "PBMC-DB2#4A_2x+DB2#4A_2y " and "PBMC-HF#15B" have 11 measurements those were removed 


